version: '3.0'

services:
  main:
    container_name: nest_server
    build:
      context: .
    env_file:
      - ./src/config/env/development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
      - 9229:9229
    command: yarn start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: nest_server_postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: nest_crud
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
